In [1]:
import pandas as pd
import numpy as np

# 1. Datos de transacciones con errores y valores nulos
datos_ventas = {
    "ID_Transaccion": ["T01", "T02", "T03", "T04", "T05", "T06", "T07"],
    "ID_Producto": ["P101", "P102", "P101", "P103", "P102", "P104", "P101"],
    "Cantidad": [2, np.nan, 1, 5, 2, np.nan, 3],
    "Precio_Unitario": [250.0, 800.0, 250.0, None, 800.0, 120.0, 250.0]
}

# 2. Catálogo maestro de productos
catalogo_productos = {
    "ID_Producto": ["P101", "P102", "P103", "P104"],
    "Nombre_Producto": ["Audífonos Bluetooth", "Monitor 24 pulg", "Teclado Mecánico", "Mouse Óptico"],
    "Categoria": ["Electrónica", "Electrónica", "Accesorios", "Accesorios"]
}

df_ventas = pd.DataFrame(datos_ventas)
df_catalogo = pd.DataFrame(catalogo_productos)

In [ ]:
df_ventas

  ID_Producto      Nombre_Producto    Categoria
0        P101  Audífonos Bluetooth  Electrónica
1        P102      Monitor 24 pulg  Electrónica
2        P103     Teclado Mecánico   Accesorios
3        P104         Mouse Óptico   Accesorios

In [13]:
df_catalogo

  ID_Producto      Nombre_Producto    Categoria
0        P101  Audífonos Bluetooth  Electrónica
1        P102      Monitor 24 pulg  Electrónica
2        P103     Teclado Mecánico   Accesorios
3        P104         Mouse Óptico   Accesorios

In [4]:
df_ventas["Cantidad"] = df_ventas["Cantidad"].fillna(1)

precio_promedio = df_ventas["Precio_Unitario"].mean()

df_ventas["Precio_Unitario"] = df_ventas["Precio_Unitario"].fillna(precio_promedio)

In [5]:
df_ventas["Total_Venta"] = df_ventas["Cantidad"] * df_ventas["Precio_Unitario"]

df_ventas

  ID_Transaccion ID_Producto  Cantidad  Precio_Unitario  Total_Venta
0            T01        P101       2.0       250.000000   500.000000
1            T02        P102       1.0       800.000000   800.000000
2            T03        P101       1.0       250.000000   250.000000
3            T04        P103       5.0       411.666667  2058.333333
4            T05        P102       2.0       800.000000  1600.000000
5            T06        P104       1.0       120.000000   120.000000
6            T07        P101       3.0       250.000000   750.000000

In [7]:
df_ventas["Tipo_Compra"] = np.where(df_ventas["Total_Venta"] > 1000, "VIP", "Normal")

df_ventas

,ID_Transaccion,ID_Producto,Cantidad,Precio_Unitario,Total_Venta,Tipo_Compra
0,T01,P101,2.0,250.000000,500.000000,Normal
1,T02,P102,1.0,800.000000,800.000000,Normal
2,T03,P101,1.0,250.000000,250.000000,Normal
3,T04,P103,5.0,411.666667,2058.333333,VIP
4,T05,P102,2.0,800.000000,1600.000000,VIP
5,T06,P104,1.0,120.000000,120.000000,Normal
6,T07,P101,3.0,250.000000,750.000000,Normal

In [9]:
df_maestro = pd.merge(df_catalogo, df_ventas, on="ID_Producto", how="inner")

df_maestro

,ID_Producto,Nombre_Producto,Categoria,ID_Transaccion,Cantidad,Precio_Unitario,Total_Venta,Tipo_Compra
0,P101,Audífonos Bluetooth,Electrónica,T01,2.0,250.000000,500.000000,Normal
1,P101,Audífonos Bluetooth,Electrónica,T03,1.0,250.000000,250.000000,Normal
2,P101,Audífonos Bluetooth,Electrónica,T07,3.0,250.000000,750.000000,Normal
3,P102,Monitor 24 pulg,Electrónica,T02,1.0,800.000000,800.000000,Normal
4,P102,Monitor 24 pulg,Electrónica,T05,2.0,800.000000,1600.000000,VIP
5,P103,Teclado Mecánico,Accesorios,T04,5.0,411.666667,2058.333333,VIP
6,P104,Mouse Óptico,Accesorios,T06,1.0,120.000000,120.000000,Normal

In [14]:
reporte_ventas = df_maestro.groupby("Categoria")["Total_Venta"].sum().reset_index()

reporte_ventas["Total_Venta"] = reporte_ventas["Total_Venta"].round(2)

reporte_ventas

     Categoria  Total_Venta
0   Accesorios      2178.33
1  Electrónica      3900.00