In [14]:
import pandas as pd
import numpy as np
from pandas import json_normalize

# 1. Datos simulados (crudos y anidados)
filas = 50_000
datos_crudos = {
    "id_transaccion": range(1, filas + 1),
    "info_cliente": [{"pais": np.random.choice(["MX", "US", "CO"]), "vip": np.random.choice([True, False])} for _ in range(filas)],
    "monto_compra": np.random.uniform(50.0, 3000.0, size=filas),
    "departamento": np.random.choice(["Electronica", "Moda", "Hogar", "Deportes"], size=filas)
}
df_sucio = pd.DataFrame(datos_crudos)

In [15]:
print(df_sucio.columns.tolist())

['id_transaccion', 'info_cliente', 'monto_compra', 'departamento']

In [16]:
df_sucio

       id_transaccion                  info_cliente  monto_compra departamento
0                   1   {'pais': 'CO', 'vip': True}   1463.269489         Moda
1                   2  {'pais': 'MX', 'vip': False}   2484.709359     Deportes
2                   3  {'pais': 'MX', 'vip': False}    240.946908        Hogar
3                   4   {'pais': 'CO', 'vip': True}    930.799756        Hogar
4                   5   {'pais': 'US', 'vip': True}   2462.590171        Hogar
...               ...                           ...           ...          ...
49995           49996  {'pais': 'US', 'vip': False}   1460.139191  Electronica
49996           49997  {'pais': 'CO', 'vip': False}    159.892191     Deportes
49997           49998  {'pais': 'MX', 'vip': False}   2952.465586     Deportes
49998           49999   {'pais': 'MX', 'vip': True}   1325.449854         Moda
49999           50000   {'pais': 'CO', 'vip': True}    854.459829     Deportes

[50000 rows x 4 columns]

In [17]:
# 1. Aplanar la lista de diccionarios agregando el prefijo solicitado
df_junto = json_normalize(df_sucio['info_cliente']).add_prefix('info_cliente.')

# 2. Concatenar las nuevas columnas y eliminar la columna original anidada
df_sucio = pd.concat([df_sucio.drop(columns=['info_cliente']), df_junto], axis=1)
df_sucio

,id_transaccion,monto_compra,departamento,info_cliente.pais,info_cliente.vip
0,1,1463.269489,Moda,CO,True
1,2,2484.709359,Deportes,MX,False
2,3,240.946908,Hogar,MX,False
3,4,930.799756,Hogar,CO,True
4,5,2462.590171,Hogar,US,True
...,...,...,...,...,...
49995,49996,1460.139191,Electronica,US,False
49996,49997,159.892191,Deportes,CO,False
49997,49998,2952.465586,Deportes,MX,False
49998,49999,1325.449854,Moda,MX,True
49999,50000,854.459829,Deportes,CO,True

In [18]:
archivo_parquet = 'transacciones_finales.parquet'
df_sucio.to_parquet(archivo_parquet, index=False, compression="snappy")
print(f"Archivo guardado y comprimido en Parquet exitosamente.")

Archivo guardado y comprimido en Parquet exitosamente.

In [19]:
# Tomamos tu df_sucio anterior y lo guardamos particionado por departamento
df_sucio.to_parquet("dataset_particionado", partition_cols=["departamento"], index=False)
print("¡Dataset particionado guardado con éxito! Revisa tu explorador de archivos.")

¡Dataset particionado guardado con éxito! Revisa tu explorador de archivos.