In [29]:
import pandas as pd
import numpy as np

evaluaciones_raw = {
    "ID_Task": ["T1", "T2", "T3", "T4"],
    "ID_Anotador": ["A10", "A11", "A10", "A12"],
    "Calificacion_Dada": [4.5, 2.0, 5.0, 3.5],
    "Calificacion_Esperada": [4.0, 4.0, 5.0, 4.0]
}

catalogo_anotadores = {
    "ID_Anotador": ["A10", "A11", "A12"],
    "Nombre": ["Ana", "Carlos", "Elena"],
    "Nivel": ["Senior", "Junior", "Junior"]
}

df_evaluaciones = pd.DataFrame(evaluaciones_raw)

df_catalogo = pd.DataFrame(catalogo_anotadores)

In [30]:
df_evaluaciones

  ID_Task ID_Anotador  Calificacion_Dada  Calificacion_Esperada
0      T1         A10                4.5                    4.0
1      T2         A11                2.0                    4.0
2      T3         A10                5.0                    5.0
3      T4         A12                3.5                    4.0

In [31]:
df_catalogo

  ID_Anotador  Nombre   Nivel
0         A10     Ana  Senior
1         A11  Carlos  Junior
2         A12   Elena  Junior

In [32]:
df_unificado = pd.merge(df_catalogo, df_evaluaciones, on = "ID_Anotador", how = "inner")

df_unificado

,ID_Anotador,Nombre,Nivel,ID_Task,Calificacion_Dada,Calificacion_Esperada
0,A10,Ana,Senior,T1,4.5,4.0
1,A10,Ana,Senior,T3,5.0,5.0
2,A11,Carlos,Junior,T2,2.0,4.0
3,A12,Elena,Junior,T4,3.5,4.0

In [33]:
df_unificado["Desviacion"] = np.abs((df_unificado["Calificacion_Dada"]) - (df_unificado["Calificacion_Esperada"]))

In [34]:
df_unificado

,ID_Anotador,Nombre,Nivel,ID_Task,Calificacion_Dada,Calificacion_Esperada,Desviacion
0,A10,Ana,Senior,T1,4.5,4.0,0.5
1,A10,Ana,Senior,T3,5.0,5.0,0.0
2,A11,Carlos,Junior,T2,2.0,4.0,2.0
3,A12,Elena,Junior,T4,3.5,4.0,0.5

In [35]:
df_recapacitacion = df_unificado.loc[df_unificado["Desviacion"] > 1]
df_recapacitacion

,ID_Anotador,Nombre,Nivel,ID_Task,Calificacion_Dada,Calificacion_Esperada,Desviacion
2,A11,Carlos,Junior,T2,2.0,4.0,2.0